### ISSUE TITLE
Upgrade to latest version of brain.js?

### ISSUE THREAD

**Issue by robertleeplummerjr** [marcusbuffett/Three.js-Neural-Network-Visualizer#1]
We would love to post your work on https://github.com/BrainJS/brain.js.  Would you be up for upgrading brain to a later version?
ty for this fantastic visualization!

**Comment by marcusbuffett** [comment]
Yeah sure, I'll upgrade to the latest version sometime this week (Depending on how long it takes to get this project running again... Been quite a while since I've touched this...)

**Comment by robertleeplummerjr** [comment]
I think you'll be fairly pleased, we're migrating to all GPU.  This ~~may~~ will get more attention, if you are up for it.

**Comment by marcusbuffett** [comment]
Yeah I'm up for it. Running into something sort of weird with the new brain js though, the new version looks more like me trying to learn something:

![brain_js_new_version](https://user-images.githubusercontent.com/1834328/36826106-1dd41e88-1cc0-11e8-8550-3a6ef6e313fe.gif)

Old version would get to an error threshold of 0.01 within ~200 iterations, this one doesn't seem to go below 0.25. I've tried tinkering a bit with the batch size hidden layers, but that's about as far as my neural network knowledge goes.

Any ideas? Has the model changed significantly in the last couple years? Training options take a different shape now? I'm not getting any console errors.

**Comment by robertleeplummerjr** [comment]
I'll check it out in the morning with the one you have installed.  If there is a problem well find it.

**Comment by marcusbuffett** [comment]
Cool, I updated the repo with the new brain.js and some more instructions on running the project

**Comment by robertleeplummerjr** [comment]
awesome!  I looked into the training functions, and at least they are very similar.  Old on left, new on right

runInput:
<img width="1209" alt="screen shot 2018-03-02 at 2 46 47 pm" src="https://user-images.githubusercontent.com/679099/36918732-d2ed4a1a-1e28-11e8-9241-24f11dc3e28d.png">

calculateDeltas:
<img width="1208" alt="screen shot 2018-03-02 at 2 41 21 pm" src="https://user-images.githubusercontent.com/679099/36918757-ec89fdce-1e28-11e8-8101-b468b2304eed.png">

adjustWeights:
<img width="1213" alt="screen shot 2018-03-02 at 2 39 57 pm" src="https://user-images.githubusercontent.com/679099/36918780-00a9e508-1e29-11e8-96d7-34f33cee0a6e.png">

But I'll keep digging.

**Comment by robertleeplummerjr** [comment]
I just checked out the version you have, and it doesn't learn at all!  Funniest thing I'm just waiting for it to....   I'll find it.

**Comment by robertleeplummerjr** [comment]
Ok, I believe this bug was handled sometime back and resolved.  I tried your project what is now v1.1.0 and it learned very fast.


<img width="1366" alt="screen shot 2018-03-03 at 2 01 52 pm" src="https://user-images.githubusercontent.com/679099/36938144-7bccb45a-1eeb-11e8-96ef-a223baeef08a.png">

We now try and assist in training a bit, so things like "learningRate" set to 0 will cause an exception.  Something to keep in mind that will need to be adjusted.

**Comment by robertleeplummerjr** [comment]
Note: v1.1.0 was just released, and was something I was dragging my feet on.

**Comment by robertleeplummerjr** [comment]
I see awesome stuff going on here man.

**Comment by marcusbuffett** [comment]
Sorry, been a hectic few weeks. Upgraded now! Had to change a couple things but it's working now as far as I can tell.
